; Listing generated by Microsoft (R) Optimizing Compiler Version 19.10.25019.0 

	TITLE	C:\hub\tinycrypt\block\xtea\xtea.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	_xtea_encrypt
; Function compile flags: /Ogspy
; File c:\hub\tinycrypt\block\xtea\xtea.c
;	COMDAT _xtea_encrypt
_TEXT	SEGMENT
_v0$1$ = -4						; size = 4
_rnds$ = 8						; size = 4
_key$ = 12						; size = 4
_buf$ = 16						; size = 4
_xtea_encrypt PROC					; COMDAT

; 32   : void xtea_encrypt(uint32_t rnds, void *key, void *buf) {

	push	ecx

; 33   :     int      i;
; 34   :     uint32_t v0, v1, t, sum=0;
; 35   :     uint32_t *k=(uint32_t*)key;
; 36   :     uint32_t *v=(uint32_t*)buf;
; 37   :     
; 38   :     v0 = v[0]; v1 = v[1];
; 39   :     
; 40   :     for (i=rnds<<1; i>0; i--) {

	mov	eax, DWORD PTR _rnds$[esp]
	mov	edx, DWORD PTR _buf$[esp]
	push	ebx
	push	ebp
	push	esi
	mov	ecx, DWORD PTR [edx]
	lea	ebx, DWORD PTR [eax+eax]
	mov	ebp, DWORD PTR [edx+4]
	xor	esi, esi
	test	ebx, ebx
	jle	SHORT $LN3@xtea_encry
	mov	edx, ecx
	push	edi
$LL4@xtea_encry:

; 41   :       t = sum;

	mov	edi, esi

; 42   :       if (i & 1) {

	test	bl, 1
	je	SHORT $LN5@xtea_encry

; 43   :         sum += 0x9E3779B9;

	sub	esi, 1640531527				; 61c88647H

; 44   :         t = sum >> 11;          

	mov	edi, esi
	shr	edi, 11					; 0000000bH
$LN5@xtea_encry:

; 45   :       }
; 46   :       v0  += ((((v1 << 4) ^ (v1 >> 5)) + v1) ^ (sum + k[t & 3]));        

	mov	ecx, ebp
	mov	eax, ebp
	shr	ecx, 5
	and	edi, 3
	shl	eax, 4
	xor	ecx, eax
	mov	eax, DWORD PTR _key$[esp+16]
	add	ecx, ebp
	mov	eax, DWORD PTR [eax+edi*4]
	add	eax, esi
	xor	ecx, eax
	add	ecx, edx
	dec	ebx

; 47   :       XCHG(v0, v1);

	mov	edx, ebp
	mov	ebp, ecx
	test	ebx, ebx
	jg	SHORT $LL4@xtea_encry
	mov	DWORD PTR _v0$1$[esp+20], edx
	mov	edx, DWORD PTR _buf$[esp+16]
	mov	ecx, DWORD PTR _v0$1$[esp+20]
	pop	edi
$LN3@xtea_encry:
	pop	esi

; 48   :     }
; 49   :     v[0] = v0; v[1] = v1;

	mov	DWORD PTR [edx+4], ebp
	pop	ebp
	mov	DWORD PTR [edx], ecx
	pop	ebx

; 50   : }

	pop	ecx
	ret	0
_xtea_encrypt ENDP
_TEXT	ENDS
END
