msvc:
	cl /nologo /DTEST /O2 /Os maru.c
	cl /nologo /DTEST /O2 /Os maru2.c  
gnu:	
	gcc -Wall -DTEST -O2 -Os maru.c -omaru
	gcc -Wall -DTEST -O2 -Os maru2.c -omaru2 
clang:
	clang -Wall -DTEST -O2 -Os maru.c -omaru
	clang -Wall -DTEST -O2 -Os maru2.c -omaru
