@echo off
_bin\sjasmplus.exe example_aplib.asm
_bin\sjasmplus.exe example_exomizer.asm
_bin\sjasmplus.exe example_hrust1.asm
_bin\sjasmplus.exe example_hrust2.asm
_bin\sjasmplus.exe example_lz4_standard.asm
_bin\sjasmplus.exe example_lz4_raw.asm
_bin\sjasmplus.exe example_megalz.asm
_bin\sjasmplus.exe example_pletter.asm
_bin\sjasmplus.exe example_pucrunch.asm
_bin\sjasmplus.exe example_zx7.asm