; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.40219.01 

	TITLE	c:\hub\tinycrypt\tbnlib\bnlib\curve.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

CONST	SEGMENT
_hydro_x25519_MONTGOMERY_FACTOR DD 012547e1bH
_hydro_x25519_sc_p DD 05cf5d3edH
	DD	05812631aH
	DD	0a2f79cd6H
	DD	014def9deH
	DD	00H
	DD	00H
	DD	00H
	DD	010000000H
_hydro_x25519_sc_r2 DD 0449c0f01H
	DD	0a40611e3H
	DD	068859347H
	DD	0d00e1ba7H
	DD	017f5be65H
	DD	0ceec73d2H
	DD	07c309a3dH
	DD	0399411bH
_hydro_x25519_BASE_POINT DB 09H
	ORG $+31
_hydro_x25519_a24 DD 01db41H
CONST	ENDS
END
